---
- name: install wireguard
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - wireguard
    - wireguard-dkms
    - wireguard-tools
    - linux-headers-{{ ansible_kernel }}

- name: enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: deploy wireguard configs
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: 0600
  loop:
    - etc/wireguard/wg0.conf
    - etc/wireguard/privatekey
    - etc/wireguard/publickey
  notify:
    - restart wireguard
